fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    systemd: "https://github.com/camptocamp/puppet-systemd"
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall"
    limits: "https://github.com/erwbgy/puppet-limits"
    file_concat: "git://github.com/electrical/puppet-lib-file_concat.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    cron_core:
      repo: https://github.com/puppetlabs/puppetlabs-cron_core.git
      puppet_version: ">= 6.0.0"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: https://github.com/puppetlabs/puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
  symlinks:
   "cvmfs": "#{source_dir}"
